#IF (LOG4CPP_FOUND)
#    SET(LOG4CPP_FIND_QUIETLY TRUE)
#ENDIF (LOG4CPP_FOUND)

FIND_PATH(LOG4CPP_INCLUDE_DIR log4cpp/FileAppender.hh
        )

FIND_LIBRARY(LOG4CPP_LIBRARIES
        NAMES liblog4cpp.so
        )

SET(LOG4CPP_FOUND 0)

IF(LOG4CPP_INCLUDE_DIR)
    IF(LOG4CPP_LIBRARIES)
        SET(LOG4CPP_FOUND 1)
    ENDIF(LOG4CPP_LIBRARIES)
ENDIF(LOG4CPP_INCLUDE_DIR)

IF(LOG4CPP_FOUND)
    MESSAGE(STATUS "Log4CPP is found.")
ENDIF(LOG4CPP_FOUND)

IF (NOT LOG4CPP_FOUND)
    MESSAGE(STATUS "Log4CPP not found. liblog4cpp5-dev is missing. Install it with your packet manager")
ENDIF(NOT LOG4CPP_FOUND)

MARK_AS_ADVANCED(
        LOG4CPP_INCLUDE_DIR
        LOG4CPP_LIBRARIES
)